### ISSUE TITLE
[Meeting] [2024/10/13] Meeting Log

### ISSUE THREAD

**Issue by sypark9646** [litmus-o11y/meeting-note#11]
## 🔎 회의 안건
- [x] 멘토님 PR 변경사항 검토
- [x] 이번주 각자 완료한 작업 공유
- [x] 작업 중요도 논의
- [x] 향후 계획

## 📚 내용 정리
- 멘토님 PR 변경사항
  - 함수명 변경: 'Chaos' 대신 'Fault'를 사용 (예: Prepare실험이름Fault)
  - serial mode / parallel mode 분기 추가
  - inject 관련 이벤트 추가
- 작업 중요도
  - span error > span attribute > span event > log
  - span attribute
     - 기본적으로 실험 관련 정보 포함
     - podname, podnamespace 등 불필요한 정보 제외할 것
     - 실험에 영향을 주지 않는 데이터만 포함
     - 다른 오픈소스의 attribute 사용 방식 참고
  - 작업 시작 시점: 일단 변경사항이 계속 있을 수 있기 때문에 멘토님 PR이 머지된 후에 작업을 시작하는 것이 효율적일 것 같다.

## 💭 ToDo
- 다음주 일요일 오프라인 밋업(멘토님 참석 여부 확인 필요)
- 이슈 올리기 (담당: 소연)
- 블로그 글쓰기 (담당: 수현, 재연)
- 추가 이슈 탐색
   - 참고: [LitmusChaos 분석 문서](https://github.com/dwelsch-esi/cncf-techdocs/blob/litmuschaos-analysis/analyses/0013-litmuschaos/litmuschaos-analysis.md)
   - 추가 기여 가능 사항 발견 시 이슈 올리기
